server:
  port: ${PORT:8989}

spring:
  application:
    name: mybatis
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.mybatis.entity

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  show-actuator: false
