server:
  port: 8989

spring:
  application:
    name: mybatis
  datasource:
    url: jdbc:postgresql://localhost:5434/mybatis
    username: phoneshop_night
    password: phoneshop123
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

