server:
  port: 8989

spring:
  application:
    name: mybatis
  datasource:
    url: jdbc:postgresql://localhost:5434/mybatis
    username: phoneshop_night
    password: phoneshop123
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.mybatis.entity

